name: Docker Image Multi-Container Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Build the Docker Image
      run: docker build -t ga63qes/react-test -f ./client/Dockerfile.dev ./client
    -
      name: Run Docker Test Container
      run: docker run -e CI=true ga63qes/react-test npm test
    - 
      name: Build Production Images and Push - Nginx
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        push: true
        tags: ga63qes/multi-nginx
    -
      name: Build Production Images and Push - Server
      uses: docker/build-push-action@v2
      with:
        context: ./server
        push: true
        tags: ga63qes/multi-server
    -
      name: Build Production Images and Push - Worker
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        push: true
        tags: ga63qes/multi-worker
    
